config/routes.rb
Rails.application.routes.draw do

  resources :casetitles do
    resources :testcases
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casetitle.rb
class Casetitle < ApplicationRecord
  has_many :testcases
end

app/models/testcase.rb
class Testcase < ApplicationRecord
  belongs_to :casetitle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/casetitles_controller.rb
class CasetitlesController < ApplicationController

  def index
    @casetitles = Casetitle.all
  end

  def show
    @casetitle = Casetitle.find(params[:id])
  end

  def new
    @casetitle = Casetitle.new
  end

  def create
    @casetitle = Casetitle.create(casetitle_params)
    if @casetitle.save(casetitle_params)
      redirect_to @casetitle
    else
      render 'new'
    end
  end

  def edit
    @casetitle = Casetitle.find(params[:id])
  end

  def update
    @casetitle = Casetitle.find(params[:id])
    if @casetitle.update(casetitle_params)
      redirect_to @casetitle
    else
      render 'new'
    end
  end

  def destroy
    @casetitle = Casetitle.find(params[:id]).destroy
    redirect_to casetitles_path
  end

  private

  def casetitle_params
    params.require(:casetitle).permit(:title, :summary)
  end

end

app/controllers/testcases_controller.rb
class TestcasesController < ApplicationController

  def create
    @casetitle = Casetitle.find(params[:casetitle_id]).testcases.create(testcase_params)
    redirect_to casetitle_path(@casetitle)
  end

  def destroy
    @casetitle = Casetitle.find(params[:casetitle_id]).testcases.find(params[:id]).destroy
    redirect_to casetitle_path(@casetitle)
  end

  private

  def testcase_params
    params.require(:testcase).permit(:texpresult, :envir, :tester)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casetitles_helper.rb
module CasetitlesHelper
end

app/helpers/testcases_helper.rb
module TestcasesHelper
end

app/views/casetitles/_form.html.erb
<%= form_for @casetitle do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/casetitles/edit.html.erb
<%= form_for @casetitle do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<br>
<%= link_to 'Back to Cases', casetitles_path %>

app/views/casetitles/index.html.erb
<h1>Cases:</h1>

<table>
  <tr>
    <th>Case Title</th>
    <th>Summary</th>
  </tr>

  <% @casetitles.each do |t| %>
    <tr>
      <td><%= t.title %></td>
      <td><%= t.summary %></td>
      <td><%= link_to 'Show', casetitle_path(t) %></td>
      <td><%= link_to 'Edit', edit_casetitle_path(t) %></td>
      <td><%= link_to 'Delete', t, method: :delete, data: {confirm: 'Are you sure ?'} %></td>
    </tr>
  <%end%>

</table>

<br>
<%= link_to 'Create New Case', new_casetitle_path %>

app/views/casetitles/new.html.erb
<h1>New Case Title</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back to Cases', casetitles_path %>

app/views/casetitles/show.html.erb
<table>
<tr>
  <th>Case Title</th>
  <th>Summary</th>
</tr>

<tr>
  <td><%= @casetitle.title %></td>
  <td><%= @casetitle.summary %></td>
</tr>
</table>

<br>

<h2>Test Cases:</h2>

<%= render @casetitle.testcases %>

<h2>Add a test case:</h2>
<%= render 'testcases/form' %>

<br>
<%= link_to 'Back to Cases', casetitles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caselist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testcases/_form.html.erb
<%= form_for([@casetitle, Testcase.new]) do |f| %>
  <p>
    <%= f.label :expresult %><br>
    <%= f.text_field :expresult %>
  </p>

  <p>
    <%= f.label :envir %><br>
    <%= f.text_field :envir %>
  </p>

  <p>
    <%= f.label :tester %><br>
    <%= f.text_field :tester %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/testcases/_testcase.html.erb
<% @casetitle.testcases.each do |testcase| %>
  <p>
    <strong>Expected Result:</strong>
    <%= testcase.expresult %>
  </p>

  <p>
    <strong>Environment:</strong>
    <%= testcase.envir %>
  </p>

  <p>
    <strong>Tester:</strong>
    <%= testcase.tester %>
  </p>

  <p>
    <%= link_to 'Destroy TStep', [testcase.casetitle, testcase],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </p>

<% end %>